CREATE ROLE usdCRE_API WITH PASSWORD 'minhasenha';

CREATE TABLE usuarios (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    senha VARCHAR(100) NOT NULL
);


CREATE DATABASE usdCRE_API;
GRANT ALL PRIVILEGES ON DATABASE usdCRE_API TO usdCRE_API;

ALTER USER usdCRE_API PASSWORD 'nova_senha';



